---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements_dev.yml
    requirements-file: requirements.yml


driver:
  name: docker


platforms:
  - name: instance
    image: "geerlingguy/docker-${SLINGNODE_DISTRO:-rockylinux8}-ansible:latest"
    command: ${SLINGNODE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true


provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  playbooks:
    converge: ../resources/playbooks/converge_docker.yml
    prepare: ../resources/playbooks/prepare.yml
  inventory:
    group_vars:
      all:
        clients:
          execution: ${SLINGNODE_EXECUTION:-geth}
          consensus: ${SLINGNODE_CONSENSUS:-lighthouse}
          validator: ${SLINGNODE_VALIDATOR:-lighthouse}


verifier:
  name: ansible


scenario:
  name: default_docker
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
