---
- name: Create JWT secret file access group
  ansible.builtin.group:
    name: "{{ jwt_secret_access_group.group }}"
    gid: "{{ jwt_secret_access_group.gid }}"
    state: present


- name: Create JWT secret directory
  ansible.builtin.file:
    path: "{{ jwt_secret_path }}"
    state: directory
    group: "{{ jwt_secret_access_group.group }}"
    mode: "0750"


- name: Check if jwt file secret file exists
  ansible.builtin.stat:
    path: "{{ jwt_secret_path }}/{{ jwt_secret_file }}"
  register: jwt_secret_stat


- name: Generate jwt secret
  ansible.builtin.shell: set -euxo pipefail && openssl rand -hex 32 | tr -d "\n" > "{{ jwt_secret_path }}/{{ jwt_secret_file }}"
  args:
    executable: /bin/bash
  register: shell_command_output
  changed_when: shell_command_output.rc == 0
  when: jwt_secret_string is undefined and not jwt_secret_stat.stat.exists or recreate_jwt | bool


- name: Copy proivded JWT secret to a file
  ansible.builtin.copy:
    content: "{{ jwt_secret_string }}"
    dest: "{{ jwt_secret_path }}/{{ jwt_secret_file }}"
    group: "{{ jwt_secret_access_group.group }}"
    mode: "0740"
  when: jwt_secret_string is defined


- name: Set JWT secret file permissions
  ansible.builtin.file:
    path: "{{ jwt_secret_path }}/{{ jwt_secret_file }}"
    state: file
    group: "{{ jwt_secret_access_group.group }}"
    mode: "0740"
