---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements_dev.yml
    requirements-file: requirements.yml


driver:
  name: vagrant
  provider:
    name: libvirt
  provision: false
  cachier: machine
  parallel: true


platforms:
  - name: instance_ubuntu2204
    hostname: slingnode-test-01
    box: generic/ubuntu2204
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
    memory: 4096
    cpus: 2
    provider_options:
      video_type: 'vga'
      driver: 'kvm'
      cpu_mode: 'host-passthrough'
      video_vram: '16384'


  - name: instance_ubuntu2004
    hostname: slingnode-test-02
    box: generic/ubuntu2004
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
    memory: 4096
    cpus: 2
    provider_options:
      video_type: 'vga'
      driver: 'kvm'
      cpu_mode: 'host-passthrough'
      video_vram: '16384'


  - name: instance_almalinux8
    hostname: slingnode-test-03
    box: almalinux/8
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
    memory: 4096
    cpus: 2
    provider_options:
      video_type: 'vga'
      driver: 'kvm'
      cpu_mode: 'host-passthrough'
      video_vram: '16384'


  - name: instance_almalinux9
    hostname: slingnode-test-04
    box: almalinux/9
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
    memory: 4096
    cpus: 2
    provider_options:
      video_type: 'vga'
      driver: 'kvm'
      cpu_mode: 'host-passthrough'
      video_vram: '16384'


provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  playbooks:
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
  inventory:
    group_vars:
      all:
        clients:
          execution: ${SLINGNODE_EXECUTION:-geth}
          consensus: ${SLINGNODE_CONSENSUS:-lighthouse}
          validator: ${SLINGNODE_VALIDATOR:-lighthouse}


verifier:
  name: ansible


scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
