---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true


  vars:
    docker_package_state: present
    docker_install_compose_plugin: true


  tasks:
    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
