---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true


  vars:
    docker_package_state: present
    docker_install_compose_plugin: true


  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'


  tasks:
    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
